# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 891113c20fe59e3eb4f59aae4a8a20be6411596109441a3c1f0b3a4e687186088c003f105781f4fc1eb70548577be26f96e8254e3f57a54abe5a576a1cf61f53

test:
  secret_key_base: fb11df4f7521a27c0ed0b33861037ab148eda9fd4c142d696a0bfcd54def3323b89d60eb0c6e208586dd437da5d905bf1200f485d1018318d66bb0693d3bec8b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
